var nama = prompt('Silahkan ketik nama anda:')
console.log(`nama: ${nama}`)
var tglahir = prompt ('ketik tanggal lahir anda:')
console.log(`tglahir: ${tglahir}`)
var alamat = prompt ('Ketik alamat lengkap anda:')
console.log(`alamat: ${alamat}`)
var pendidikan = prompt ('ketik pendidikan terakhir anda:')
console.log(`pendidikan: ${pendidikan}`)
var profesi = prompt ('ketik profesi anda:')
console.log(`profesi: ${profesi}`)
